Add RAG evaluation example
vessl-ai/examples pull request #50
Opened 2024-07-10 10:24 UTC by lee-saint

곧 나갈 블로그 포스트의 RAG 평가 파이프라인을 돌리는 코드입니다.
블로그 포스트가 올라가면 readme에 블로그 포스트 링크를 추가해야 할 필요가 있습니다.

2024-07-10 11:32 UTC, hippothewild requested changes

2024-07-10 11:32 UTC, hippothewild commented on rag-evaluation/1-data-ingestion.py
> +chroma_path = os.environ.get("CHROMA_PATH", "/chroma")
환경변수보다는 argparse로 받고 로직을 main 함수로 실행하는게 좋을것 같습니다.

2024-07-10 11:32 UTC, hippothewild commented on rag-evaluation/1-data-ingestion.py
> +        model_kwargs={"device": "cuda"},
cuda로 가정하기보단 torch.is_cuda_available 을 쓰는게 좋을듯

2024-07-10 11:32 UTC, hippothewild commented on rag-evaluation/1-data-ingestion.py
> +for page in data["wikipedia_pages"]:
n 카운트하기보단 data["wikipedia_pages"][:20000]?

2024-07-10 11:32 UTC, hippothewild commented on rag-evaluation/2-rag-chain.py
> +chroma_path = os.environ.get("CHROMA_PATH", "/chroma")
ditto

2024-07-10 11:32 UTC, hippothewild commented on rag-evaluation/2.1-raw-llm-chain.py
> +data_path = os.environ.get("DATA_PATH", "/data")
ditto

2024-07-10 11:32 UTC, hippothewild commented on rag-evaluation/README.md
> +## Citation
HyDE랑 RAGAS도 cite해야하는지 확인해보고 해야 한다면 여기에 추가해두면 좋을것 같습니다

2024-07-10 11:32 UTC, hippothewild commented on rag-evaluation/README.md
> +For further details, please refer to our blog post.
뽑아둔 result같은거 있으면 expected result 차트 하나 붙여둬도 될것같습니다

2024-07-10 11:32 UTC, hippothewild commented on rag-evaluation/3-rag-evaluation.py
> +results = evaluate(
엄청나게 오래 걸리거나 토큰을 많이 잡아먹지 않나요? 그렇다면 README에 경고해두는게 좋을듯

2024-07-10 11:32 UTC, hippothewild commented on rag-evaluation/3-rag-evaluation.py
> +    model_kwargs={"device": "cuda"},
ditto (cuda)

2024-07-10 11:32 UTC, hippothewild commented on rag-evaluation/3-rag-evaluation.py
> +    max_tokens=1024,
max token이 이걸로는 적지 않나요? 전체 프롬프트 길이가 꽤 길것같은데

2024-07-11 00:04 UTC, lee-saint commented on rag-evaluation/1-data-ingestion.py
> +for page in data["wikipedia_pages"]:
이건 데이터셋에 빈 값이 생각보다 많아서 이렇게 짰습니다. 다시 확인해 보니 20만 건에 빈 값이 5,500건 정도 되네요

2024-07-11 00:48 UTC, lee-saint commented on rag-evaluation/3-rag-evaluation.py
> +    max_tokens=1024,
output(generate) 토큰 길이로 한정이라서 evaluation 값만 나오는 거면 길 필요 없겠지 생각해서 짧게 잡았는데 좀 늘려도 되겠네요

2024-07-11 08:04 UTC, hippothewild approved these changes
rag-results-2.png에  Naiva RAG, HyDE, Reranking, Hyde+Reranking 에 쓴 모델은 무엇인가요? (라마인줄 알았는데 라마는 또 따로있어서)

2024-07-11 08:05 UTC, lee-saint commented
그것은 라마가 맞고 저 라마는 RAG를 적용하지 않은 raw 라마입니다

2024-07-11 08:14 UTC, lee-saint commented
> rag-results-2.png에 Naiva RAG, HyDE, Reranking, Hyde+Reranking 에 쓴 모델은 무엇인가요? (라마인줄 알았는데 라마는 또 따로있어서)

이 부분이 명확하지 않은 것 같아서 이미지를 업데이트했습니다

2024-07-11 08:15 UTC, merged