Add a template for hyperparameter tuning with VESSL Run
vessl-ai/examples pull request #54
Opened 2024-07-31 08:08 UTC by lee-saint

Deprecate될 예정인 Sweep을 대신하여 Run을 이용해 하이퍼파라미터 튜닝을 할 수 있는 예시입니다.

Run yaml 파일을 jinja 템플릿으로 만들어 놓고, 파라미터 목록을 딕셔너리로 주면 각 조합마다 별도의 Run을 띄웁니다.

`deprecated/mnist` 폴더의 MNIST 학습 스크립트를 실행하는 것으로 되어 있어, MNIST 폴더 디렉토리가 변경되면 여기서도 변경해야 합니다.

2024-07-31 08:16 UTC, hippothewild requested changes

2024-07-31 08:16 UTC, hippothewild commented on runs/hyperparameter-tuning/hpt.py
> +}
지금은 grid search만 구현해두셨는데, random이나 bayesian도 구현해보면 좋을것 같습니다
(bayesian은 아마 실제 돈 학습의 결과에 의존하는 기법일거라 어렵다면 random만이라도)

2024-08-02 07:02 UTC, lee-saint commented on runs/hyperparameter-tuning/hpt.py
> +}
Grid와 random search를 좀 더 명확하게 표시해서 추가했습니다

2024-08-02 07:02 UTC, hippothewild requested changes

2024-08-02 07:02 UTC, hippothewild commented on runs/hyperparameter-tuning/README.md
> +    lr_count = 2
random search의 정의가 전체 바운더리에서 랜덤 n개 뽑는거라, 여러 dimension이 있는 상황에서 랜덤하게 n개 고르는 알고리즘으로 구현해야 할 것 같습니다.

2024-08-08 03:17 UTC, hippothewild approved these changes
lgtm!

2024-08-08 04:21 UTC, merged